### ISSUE TITLE
Adding Content to Drawer

### ISSUE THREAD

**Issue by HimeshNayak** [Harshit564/AapKaVaidya#10]
The drawer is displayed after double tap on the menu icon. The empty space can be replaced by the actual menu content.

**Comment by HimeshNayak** [comment]
I can fix this issue. Please assign it to me under SWOC2020. 

Thank you

**Comment by sid-1207** [comment]
Hey I can resolve this issue.
Can you please assign it to me?

**Comment by HimeshNayak** [comment]
I have added the animation again and added a text in the empty part of the drawer. Please review the PR #12
