### ISSUE TITLE
Implement Facebook sign-in

### ISSUE THREAD

**Issue by Harshit564** [Harshit564/AapKaVaidya#3]
Is your feature request related to a problem? Please describe.
Right now, the login buttons are non-functional. The user is taken to the next page without any verification or login process. Implement Facebook Sign-In for the app.

Describe the solution you'd like
Firebase can be used to implement the Sign-In process. On clicking the Facebook Sign In button, the person should be prompted to choose from his ids. He/She should be taken to the next page on successful login.

Additional context
Ensure that you do not hard code any strings in the app. All strings should be added to the strings.dart file.

**Comment by Yashank18** [comment]
I would like to work on it under SCI

**Comment by baquer** [comment]
@Yashank18, Yeah sure! go ahead.

**Comment by Harshit564** [comment]
> I would like to work on it under SCI

Give your email id I will add to the firebase

**Comment by Yashank18** [comment]
@Harshit564  
My e-mail id - yashank7696@gmail.com

**Comment by Harshit564** [comment]
> @Harshit564
> My e-mail id - [yashank7696@gmail.com](mailto:yashank7696@gmail.com)

Cool!!
